# Generated by Django 5.1.3 on 2025-09-11 12:59

import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('edicao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.funcoes.validate_cpf])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[relacionamentos.validators.funcoes.validate_cpf])),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.magazine')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='relacionamentos.Publication', to='relacionamentos.magazine'),
        ),
        migrations.AddField(
            model_name='paper',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('magazines', models.ManyToManyField(blank=True, null=True, to='relacionamentos.magazine')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter')),
            ],
        ),
    ]
