# Generated by Django 5.0 on 2025-11-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'permissions': [('generate_code', 'Can generate code')]},
        ),
        migrations.AlterField(
            model_name='magazine',
            name='edicao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
