# Generated by Django 5.1.3 on 2025-09-11 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('turno', models.CharField(blank=True, max_length=8, null=True)),
                ('nota', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('ingresso', models.BooleanField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('informacoes', models.TextField()),
                ('guia', models.BooleanField()),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('participantes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
