# Generated by Django 5.1.3 on 2025-08-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='atividade',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turno',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
